test_data = {
    'D4': ('D4', 'W.O. No.', 'TARIL/TECH/ED/035-01-R0', None, None),
    'D5': ('D5', 'Designer', None, None, None),
    'F8': ('F8', 1.0, None, None, None),
    'J8': ('J8', 4.0, None, None, None),
    'F9': ('F9', 2.0, None, None, None),
    'J9': ('J9', 5.0, None, None, None),
    'F10': ('F10', 3.0, None, None, None),
    'J10': ('J10', 6.0, None, None, None),
    'D14': ('D14', 'Project', None, None, None),
    'D15': ('D15', 'Standard', None, None, None),
    'D16': ('D16', 'Location ', None, None, None),
    'H16': ('H16', 'Frequency ', None, None, None),
    'K16': ('K16', 'Altitude', None, None, None),
    'D17': ('D17', 'Corrosion ', None, None, None),
    'H17': ('H17', 'Seismic Zone', None, None, None),
    'K17': ('K17', 'Shade', None, None, None),
    'D18': ('D18', 'Product', 'C4', None, None),
    'F18': ('F18', 'Phases', None, None, None),
    'H18': ('H18', 'Qty', None, None, None),
    'D19': ('D19', 'MVA', None, None, None),
    'J19': ('J19', 'Design Temp', None, None, None),
    'K19': ('K19', 'Design Temp', None, None, None),
    'D20': ('D20', 'Voltage-HV', None, None, None),
    'E20': ('E20', 'Voltage-HV', 'Termination', None, None),
    'F20': ('F20', 'Voltage-HV', 'kVp', None, None),
    'G20': ('G20', 'Voltage-HV', 'SI', None, None),
    'H20': ('H20', 'Voltage-HV', 'kVrms', None, None),
    'J20': ('J20', 'Cooling', None, None, None),
    'D21': ('D21', 'Voltage-IV', None, None, None),
    'E21': ('E21', 'Voltage-IV', 'Termination', None, None),
    'F21': ('F21', 'Voltage-IV', 'kVp', None, None),
    'G21': ('G21', 'Voltage-IV', 'SI', None, None),
    'H21': ('H21', 'Voltage-IV', 'kVrms', None, None),
    'J21': ('J21', 'Cooling', None, None, None),
    'D22': ('D22', 'Voltage-LV', None, None, None),
    'E22': ('E22', 'Voltage-LV', 'Termination', None, None),
    'F22': ('F22', 'Voltage-LV', 'kVp', None, None),
    'G22': ('G22', 'Voltage-LV', 'SI', None, None),
    'H22': ('H22', 'Voltage-LV', 'kVrms', None, None),
    'J22': ('J22', 'Temp Rise', None, None, None),
    'D23': ('D23', 'Voltage-N', None, None, None),
    'E23': ('E23', 'Voltage-N', 'Termination', None, None),
    'F23': ('F23', 'Voltage-N', 'kVp', None, None),
    'G23': ('G23', 'Voltage-N', 'SI', None, None),
    'H23': ('H23', 'Voltage-N', 'kVrms', None, None),
    'J23': ('J23', 'Gradient', None, None, None),
    'K23': ('K23', 'Gradient', None, None, None),


    'D43': ('D43', 'FD (Tesla)', None, None, None),
    'F43': ('F43', 'Cl No.', None, None, None),
    'I43': ('I43', 'Transport Weight', None, None, None),
    'L43': ('L43', 'Cl No.', None, None, None),
    'D44': ('D44', 'CD (A/mm2)', None, None, None),
    'F44': ('F44', 'Cl No.', None, None, None),
    'I44': ('I44', 'Transport Dim', None, None, None),
    'L44': ('L44', 'Cl No.', None, None, None),
    'D45': ('D45', 'Linearity', None, None, None),
    'F45': ('F45', 'Cl No.', None, None, None),
    'I45': ('I45', 'Tank plate sizes', None, None, None),
    'L45': ('L45', 'Cl No.', None, None, None),
    'D46': ('D46', 'Conductor', None, None, None),
    'F46': ('F46', 'Cl No.', None, None, None),
    'I46': ('I46', 'Tank Type ', None, None, None),
    'L46': ('L46', 'Cl No.', None, None, None),
    'D47': ('D47', 'Paper type', None, None, None),
    'F47': ('F47', 'Cl No.', None, None, None),
    'I47': ('I47', 'Tertiary loaded ?', None, None, None),
    'L47': ('L47', 'Cl No.', None, None, None),
    'D48': ('D48', 'Core Grade', None, None, None),
    'F48': ('F48', 'Cl No.', None, None, None),
    'I48': ('I48', 'Parallel Operation ?', None, None, None),
    'L48': ('L48', 'Cl No.', None, None, None),
    'D49': ('D49', 'Over Fluxing', None, None, None),
    'F49': ('F49', 'Cl No.', None, None, None),
    'I49': ('I49', 'Oil Type', None, None, None),
    'L49': ('L49', 'Cl No.', None, None, None),
    'I44': ('I44', 'Transport Dim', None, None, None),
    'L44': ('L44', 'Cl No.', None, None, None),
    'D45': ('D45', 'Linearity', None, None, None),
    'F45': ('F45', 'Cl No.', None, None, None),
    'I45': ('I45', 'Tank plate sizes', None, None, None),
    'L45': ('L45', 'Cl No.', None, None, None),
    'D46': ('D46', 'Conductor', None, None, None),
    'F46': ('F46', 'Cl No.', None, None, None),
    'I46': ('I46', 'Tank Type ', None, None, None),
    'L46': ('L46', 'Cl No.', None, None, None),
    'D47': ('D47', 'Paper type', None, None, None),
    'F47': ('F47', 'Cl No.', None, None, None),
    'I47': ('I47', 'Tertiary loaded ?', 'Conventional', None, None),
    'L47': ('L47', 'Cl No.', None, None, None),
    'D48': ('D48', 'Core Grade', None, None, None),
    'F48': ('F48', 'Cl No.', None, None, None),
    'I48': ('I48', 'Parallel Operation ?', 'Yes', None, None),
    'L48': ('L48', 'Cl No.', None, None, None),
    'D49': ('D49', 'Over Fluxing', None, None, None),
    'F49': ('F49', 'Cl No.', None, None, None),
    'I49': ('I49', 'Oil Type', 'No', None, None),
    'L49': ('L49', 'Cl No.', None, None, None),



    'D53': ('D53', 'Bushing', None, None, None),
    'F53': ('F53', 'N', None, None, None),
    'H53': ('H53', 'HV', None, None, None),
    'J53': ('J53', 'LV', None, None, None),
    'L53': ('L53', 'IV', 'Cl No.', None, None),
    'D54': ('D54', 'Tap changer', None, None, None),
    'G54': ('G54', 'Tap changer', 'HV', None, None),
    'J54': ('J54', None, None, None, None),
    'L54': ('L54', None, 'Cl No.', None, None),
    'D55': ('D55', 'FOS', None, None, None),
    'L55': ('L55', None, 'Cl No.', None, None),
    'D56': ('D56', 'Oil DGA', None, None, None),
    'L56': ('L56', None, 'Cl No.', None, None),
    'D57': ('D57', 'NIFPS', None, None, None),
    'L57': ('L57', None, 'Cl No.', None, None),
    'D58': ('D58', 'BCT', None, None, None),
    'L58': ('L58', None, 'Cl No.', None, None),
    'E59': ('E59', 'Online Drying out System', None, None, None),
    'L59': ('L59', None, 'Cl No.', None, None),
    'E60': ('E60', 'Transformer monitoring system', None, None, None),
    'L60': ('L60', None, 'Cl No.', None, None),
    'E61': ('E61', 'Thermo Syphon Filter', None, None, None),
    'L61': ('L61', None, 'Cl No.', None, None),
    'E62': ('E62', 'Maintenance free Breather', None, None, None),
    'L62': ('L62', None, 'Cl No.', None, None),
    'E63': ('E63', 'Digital RTCC/ BCU', None, None, None),
    'L63': ('L63', None, 'Cl No.', None, None),
    'E64': ('E64', 'Radiator type', None, None, None),
    'L64': ('L64', None, 'Cl No.', None, None),
    'E65': ('E65', 'Other 1', None, None, None),
    'L65': ('L65', None, 'Cl No.', None, None),
    'E66': ('E66', 'Other 2', None, None, None),
    'L66': ('L66', None, 'Cl No.', None, None),
    'E67': ('E67', 'Other 3', None, None, None),
    'L67': ('L67', None, 'Cl No.', None, None),
    'E68': ('E68', 'Miscellanious fittings ', None, None, None),
    'L68': ('L68', None, 'Cl No.', None, None),


    'B73': ('B73', None, 'Cl No.', None, None),
    'D73': ('D73', None, 'Page No.', None, None),
    'E73': ('E73', None, 'Note', None, None),
    'B74': ('B74', None, 'Cl No.', None, None),
    'D74': ('D74', None, 'Page No.', None, None),
    'E74': ('E74', None, 'Note', None, None),
    'B75': ('B75', None, 'Cl No.', None, None),
    'D75': ('D75', None, 'Page No.', None, None),
    'E75': ('E75', None, 'Note', None, None),
    'B76': ('B76', None, 'Cl No.', None, None),
    'D76': ('D76', None, 'Page No.', None, None),
    'E76': ('E76', None, 'Note', None, None),
    'B77': ('B77', None, 'Cl No.', None, None),
    'D77': ('D77', None, 'Page No.', None, None),
    'E77': ('E77', None, 'Note', None, None),
    'B78': ('B78', None, 'Cl No.', None, None),
    'D78': ('D78', None, 'Page No.', None, None),
    'E78': ('E78', None, 'Note', None, None),
    'B79': ('B79', None, 'Cl No.', None, None),
    'D79': ('D79', None, 'Page No.', None, None),
    'E79': ('E79', None, 'Note', None, None),
    'B80': ('B80', None, 'Cl No.', None, None),
    'D80': ('D80', None, 'Page No.', None, None),
    'E80': ('E80', None, 'Note', None, None),
    'B81': ('B81', None, 'Cl No.', None, None),
    'D81': ('D81', None, 'Page No.', None, None),
    'E81': ('E81', None, 'Note', None, None),
    'B82': ('B82', None, 'Cl No.', None, None),
    'D82': ('D82', None, 'Page No.', None, None),
    'E82': ('E82', None, 'Note', None, None),
    'B83': ('B83', None, 'Cl No.', None, None),
    'D83': ('D83', None, 'Page No.', None, None),
    'E83': ('E83', None, 'Note', None, None),
    'B84': ('B84', None, 'Cl No.', None, None),
    'D84': ('D84', None, 'Page No.', None, None),
    'E84': ('E84', None, 'Note', None, None)
}

def check_if_output_is_correct(output):
    for coordinate, op in output.items():
        if coordinate in test_data:
            td = test_data[coordinate]
            if td[0] != coordinate or td[1] != op[1] or td[2] != op[2] or td[3] != op[3] or td[4] != op[4]:
                print(f"{op} did not match with test data")

    print("All test data matched")
    return True
